# Generated by Django 3.0.3 on 2020-02-17 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='имя объекта')),
                ('image', models.ImageField(blank=True, upload_to='art_images')),
                ('short_desc', models.CharField(blank=True, max_length=60, verbose_name='краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='описание объекта')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='стоимость')),
                ('location', models.CharField(max_length=128, verbose_name='место')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ArtCategory')),
            ],
        ),
    ]
