# Generated by Django 3.0.3 on 2020-02-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_artobjects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtObjects',
            new_name='ArtObject',
        ),
    ]
