# Generated by Django 3.0.3 on 2020-02-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200217_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('city', models.CharField(max_length=128, verbose_name='city')),
                ('address', models.CharField(max_length=254, verbose_name='address')),
            ],
        ),
        migrations.AlterField(
            model_name='artcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='artcategory',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='artist',
            field=models.CharField(blank=True, max_length=60, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='description',
            field=models.TextField(blank=True, verbose_name='artobject descriptio'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='location',
            field=models.CharField(max_length=128, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='name',
            field=models.CharField(max_length=128, verbose_name='artobject name'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='price'),
        ),
    ]
