# Generated by Django 3.0.3 on 2020-02-19 09:38

from django.db import migrations

def forwards_func(apps, schema_editor):
    art_cat_model = apps.get_model("mainapp", "ArtCategory")
    artobj_model = apps.get_model("mainapp", "ArtObject")
    con_model = apps.get_model("mainapp", "Contact")

    art_cat_obj = art_cat_model.objects.create(
        pk=1,
        name="Renaissance",
        description="Greatest masterpieces from Giotto to El Greco"
    )

    artobj_model.objects.create(
        pk=1,
        category=art_cat_obj,
        name="The Duke and Duchess of Urbino",
        image="art_images/Piero_della_Francesca_Urbino.jpg",
        artist="Piero della Francesca",
        description="It is one of the most famous works of the Italian Renaissance",
        price=180000000,
        location="Uffizi Gallery",
    )

    art_cat_obj2 = art_cat_model.objects.create(
        pk=2,
        name="Flemish Art",
        description="Astonishing paintings of old dutch masters"
    )

    artobj_model.objects.create(
        pk=2,
        category=art_cat_obj2,
        name="The Night Watch",
        image="art_images/nightwatch.jpg",
        artist="Rembrandt Harmenszoon van Rijn",
        description="The Night Watch is one of the most famous Dutch Golden Age paintings",
        price=350000000,
        location="Rijksmuseum",
    )

    art_cat_obj3 = art_cat_model.objects.create(
            pk=3,
            name="French Impressionism",
            description="Radicals of 19th century"
        )

    artobj_model.objects.create(
        pk=3,
        category=art_cat_obj3,
        name="Dance at Le Moulin de la Galette",
        image="art_images/Renoir_Le_Moulin_de_la_Galette.jpg",
        artist="Pierre-Auguste Renoir",
        description="One of Impressionism's most celebrated masterpieces",
        price=98000000,
        location="Musée d'Orsay",
    )

    con_model.objects.create(
        pk=1,
        phone="+44 (0) 20 7293 5000",
        email="enquiries@sothebys.com",
        city="London",
        address="34-35 New Bond Street"
    )

    con_model.objects.create(
        pk=2,
        phone="+44 (0) 20 7839 9060",
        email="collectionsparkroyal@christies.com",
        city="London",
        address="8 King Street"
    )

def reverse_func(apps, schema_editor):
    art_cat_model = apps.get_model("mainapp", "ArtCategory")
    con_model = apps.get_model("mainapp", "Contact")

    art_cat_model.objects.all().delete()
    con_model.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200219_0938'),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
