# Generated by Django 3.0.3 on 2020-02-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200219_0938'),
        ('mainapp', '0006_fill_db'),
    ]

    operations = [
    ]
