# Generated by Django 3.0.3 on 2020-02-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_merge_20200219_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='artcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='category is active'),
        ),
    ]
