# Generated by Django 3.0.3 on 2020-03-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_artcategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='artobject',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='art object is active'),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='description',
            field=models.TextField(blank=True, verbose_name='artobject description'),
        ),
    ]
